version: "3.9"

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/var/www/
    cap_add:
      - SYS_PTRACE
    networks:
      - appnetwork
    command: sh -c 'composer install && php-fpm'
    working_dir: /var/www/

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm
    networks:
      - appnetwork

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - appnetwork

volumes:
  db_data:

networks:
  appnetwork:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge